Repository CloneCoding-Pinterest/PinterestBE, pull requests merged in 2022-08, with the labels that each got.

#4 PR : Install `cors` `joi` `jsonwebtoken`
  package-lock.json
  package.json
Labels: library

#5 PR : sequelize migration model 수정(userPin, pinComment)
  src/layers/controllers/pin.controller.js
  src/layers/repositories/pin.repository.js
  src/layers/routers/pin.router.js
  src/layers/services/pin.service.js
  src/sequelize/migrations/z-create-pin-comment.js
  src/sequelize/migrations/z-create-user-pin.js
  src/sequelize/models/pincomment.js
  src/sequelize/models/userpin.js
Labels: bug

#7 PR : Kakao API 호출을 위해서 axios 설치
  src/index.js
  src/layers/_.router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/auth.router.js
  src/layers/services/auth.service.js
  src/sequelize/backup/create-user.js
  src/sequelize/backup/user.js
  src/sequelize/migrations/create-pin-tokens.js
  src/sequelize/migrations/create-sns-tokens.js
  src/sequelize/migrations/create-user-detail.js
  src/sequelize/migrations/create-user.js
  src/sequelize/models/pintokens.js
  src/sequelize/models/snstokens.js
  src/sequelize/models/user.js
  src/sequelize/models/userdetail.js
Labels: library

#15 PR : unloginUserGuard 구현, 토큰 검증하고 req.body 안에 payload 넣기
  package-lock.json
  package.json
  src/index.js
  src/layers/_.router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/pin.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/pin.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routers/auth.router.js
  src/layers/routers/pin.router.js
  src/layers/services/auth.service.js
  src/layers/services/pin.service.js
  src/middlewares/_.middle.loader.js
  src/middlewares/guards/unlogin.user.guard.js
  src/modules/_.module.loader.js
  src/modules/providers/jwt.provider.js
  src/modules/providers/kakao.provider.js
  src/sequelize/backup/create-user.js
  src/sequelize/backup/user.js
  src/sequelize/migrations/create-pin-tokens.js
  src/sequelize/migrations/create-sns-tokens.js
  src/sequelize/migrations/create-user-detail.js
  src/sequelize/migrations/create-user.js
  src/sequelize/migrations/z-create-pin-comment.js
  src/sequelize/migrations/z-create-user-pin.js
  src/sequelize/models/pincomment.js
  src/sequelize/models/pintokens.js
  src/sequelize/models/snstokens.js
  src/sequelize/models/user.js
  src/sequelize/models/userdetail.js
  src/sequelize/models/userpin.js
  test.js
Labels: enhancement

#16 PR : unloginUserGuard 구현, 토큰 검증하고 req.body 안에 payload 넣기
  src/middlewares/_.middle.loader.js
  src/middlewares/guards/unlogin.user.guard.js
Labels: enhancement

#21 PR : 테스트 코드 작성을 위한 `jest`, `supertest` etc...
  jest.config.json
  package-lock.json
  package.json
  test/integeration/integration.md
  test/unit/unit.md
Labels: library

#22 PR : Feature 반환 형식 공급자 함수 구현
  src/models/_.models.loader.js
  src/models/form/form.dto.js
  src/modules/_.module.loader.js
  src/modules/providers/form.provider.js
Labels: enhancement

#27 PR : API PIN 도메인 에러처리 refactoring
  src/layers/controllers/pin.controller.js
  src/layers/repositories/pin.repository.js
  src/layers/repositories/user.repository.js
  src/layers/services/auth.service.js
  src/layers/services/pin.service.js
Labels: enhancement

#28 PR : API COMMENT 도메인 에러처리 refactoring
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/services/comment.service.js
Labels: enhancement

#30 PR : Comment 예외처리 (게시글이 없을때)
  src/layers/services/comment.service.js
Labels: enhancement

#31 PR : 로그아웃 기능 구현
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/auth.router.js
  src/layers/services/auth.service.js
Labels: enhancement

#32 Pinterest-Server @ 1.0.0
  .gitignore
  app.js
  jest.config.json
  package-lock.json
  package.json
  src/index.js
  src/layers/_.router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/pin.controller.js
  src/layers/controllers/user.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/pin.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routers/auth.router.js
  src/layers/routers/comment.router.js
  src/layers/routers/global.router.js
  src/layers/routers/pin.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/pin.service.js
  src/layers/services/user.service.js
  src/middlewares/_.middle.loader.js
  src/middlewares/guards/unlogin.user.guard.js
  src/middlewares/handler/exception.handler.js
  src/middlewares/s3/.gitignore
  src/middlewares/s3/s3.md
  src/middlewares/s3/s3.middleware.js
  src/models/_.models.loader.js
  src/models/form/form.dto.js
  src/modules/_.module.loader.js
  src/modules/providers/form.provider.js
  src/sequelize/migrations/create-pin.js
  src/sequelize/migrations/z-create-pin-comment.js
  src/sequelize/migrations/z-create-user-pin.js
  src/sequelize/models/pin.js
  src/sequelize/models/pincomment.js
  test.js
  test/integeration/integration.md
  test/unit/unit.md
Labels: enhancement
